# Generated by Django 5.2.4 on 2025-07-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='mood_level',
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_type',
            field=models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('angry', 'Angry'), ('tired', 'Tired'), ('motivated', 'Motivated')], default='neutral', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
