# Generated by Django 5.2.4 on 2025-07-13 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_mood_mood_level_mood_mood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='mood_type',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='note',
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_level',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], default=3),
        ),
        migrations.AddField(
            model_name='mood',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='activity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Yoga', 'Yoga'), ('Stretching', 'Stretching'), ('Walking', 'Walking'), ('Cycling', 'Cycling'), ('Other', 'Other')], default='Cardio', max_length=100),
        ),
    ]
