# Generated by Django 5.2.4 on 2025-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_mood_mood_type_remove_mood_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood_level',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], default=3),
        ),
    ]
