# Generated by Django 5.2.4 on 2025-07-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_workout_title_workout_type_workout_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(default='Cardio', max_length=50),
        ),
    ]
