# Generated by Django 5.2.4 on 2025-07-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(default='Cardio', max_length=100),
        ),
    ]
